sudo: false
language: node_js
install:
  - npm ci
  - npm run build
script: npm run test
node_js:
  - "stable"
deploy:
  provider: npm
  email: "icoloma@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
